### ISSUE TITLE
unrecognized arguments: --floodSMS

### ISSUE THREAD

**Issue by theaasaa** [youhacker55/SMSFlooder#1]
[~/SMSFlooder]
└─$ python3 youssef.py --floodSMS --target 000000000000 --threads 5 --timeout 5
usage: youssef.py [-h] [--target  Target phone] [--flood SMS] [--timeout timeout] [--threads threads]
youssef.py: error: unrecognized arguments: --floodSMS

**Comment by youhacker55** [comment]
you forgot space  python3 youssef.py --flood SMS --target 000000000000 --threads 5 --timeout 5
